app/urls.py
# app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('check_ip/', views.check_ip, name='check_ip'),
    path('check_ip_virustotal/', views.check_ip_virustotal, name='check_ip_virustotal'),
    path('check_domain_virustotal/', views.check_domain_virustotal, name='check_domain_virustotal'),
    path('check_url_virustotal/', views.check_url_virustotal, name='check_url_virustotal'),
    path('check_hash_virustotal/', views.check_hash_virustotal, name='check_hash_virustotal'),
    path('check_user_agent/', views.check_user_agent, name='check_user_agent'),
    path("healthz/", views.healthz, name="healthz"),
    path('send_ip_statistics/', views.save_ip_statistics, name='send_ip_statistics'),
    path('send_ip_vt_statistics/', views.save_ip_vt_statistics, name='send_ip_vt_statistics'),
    path('send_domain_statistics/', views.save_domain_statistics, name='send_domain_statistics'),
    path('send_user_agent_statistics/', views.save_user_agent_statistics, name='send_user_agent_statistics'),
    path('send_url_statistics/', views.save_url_statistics, name='send_url_statistics'),
    path('send_hash_statistics/', views.save_hash_statistics, name='send_hash_statistics'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

bulkintel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500

urlpatterns = [
    path('administration/', admin.site.urls),
    path('', include('auth_app.urls')),
    path('', include('app.urls')),  # Adjust this line if your app is named differently
    path('', include('analytics.urls')),  # Include analytics URLs
]
# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Error handlers
handler400 = "auth_app.views.error_400"   # Bad Request
handler403 = "auth_app.views.error_403"   # Permission Denied
handler404 = "auth_app.views.error_404"   # Page Not Found
handler500 = "auth_app.views.error_500"   # Server Error

app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BulkIntel Reputation Checker</title>
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
    <link rel="icon" href="{% static 'app/icons/favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <div class="header">
        <img src="{% static 'app/icons/favicon.ico' %}" alt="App Icon" class="app-icon">
        <div class="user-info">
            <p>Hello, {{ request.user.username }}</p>
            <form action="{% url 'app:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="logout-button">Logout</button>
            </form>        
        </div>
    </div>

    <div class="input-section">
        <textarea id="ip_input" class="ip-textarea" placeholder="Enter IPs, URLs, domains or user agents here (one per line)..."></textarea>
        <div class="buttons-container">
            <button id="check_abuseipdb" class="check-button">Check IP on AbuseIPDB</button>
            <button id="check_virustotal" class="check-button">Check IP on VirusTotal</button>
            <button id="check_url_virustotal" class="check-button">Scan URL on VirusTotal</button>
            <button id="check_domain_virustotal" class="check-button">Check domain on on VirusTotal</button>
            <button id="check_hash_virustotal" class="check-button">Check HASH on on VirusTotal</button>
            <button id="check_user_agent" class="check-button">Check user agent</button>
        </div>
    </div>

    <div id="results_table" class="results-section">
        <!-- Results will be displayed here by JavaScript -->
    </div>

    <div class="leaderboard-card">
        <div class="leaderboard-header">
            <h2 class="leaderboard-title">Statistics</h2>
            <div class="leaderboard-controls">
            <label for="lb_entity">Indicator:</label>
            <select id="lb_entity">
                <option value="ip">IP</option>
                <option value="domain">Domain</option>
                <option value="url">URL</option>
                <option value="hash">Hash</option>
                <option value="ua">User Agent</option>
            </select>

            <label for="lb_period">Period:</label>
            <select id="lb_period">
                <option value="day">Today</option>
                <option value="week">This week</option>
                <option value="month">This month</option>
            </select>
            </div>
        </div>
        <div id="leaderboard_results" class="leaderboard-body"></div>
    </div>

    
    <script src="{% static 'app/js/index.js' %}"></script>
   
</body>
</html>